In [18]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4,5,-5,3])
obj

0    4
1    5
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  5, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [9]:
obj

Bob      4
Steve    5
Jeff    -5
Ryan     3
dtype: int64

In [10]:
obj2 = pd.Series([4,7,-5,3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
'b' in obj2

True

In [23]:
'e' in obj2

False

In [24]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [26]:
obj4 = pd.Series(sdata, index=states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001,2002,2001,2002,2003],
       'pop' : [1.5,1.7,3.6,2.4,2.9,3.2]}

In [36]:
frame = pd.DataFrame(data)

In [37]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [39]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [40]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five','six'])

In [41]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [49]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [52]:
frame2['easter'] = frame2.state =='Ohio'

In [53]:
frame2

year   state  pop  debt  easter
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

In [54]:
del frame2['easter']

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
pop = {'Nevada':{2001:2.4,2002: 2.9},
      'Ohio': {2000:1.5, 2001:1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)

In [63]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [58]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [59]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [62]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [64]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [67]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [68]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [69]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [70]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [71]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [72]:
index = obj.index

In [73]:
index

Index(['a', 'b', 'c'], dtype='object')

In [74]:
index[1:]

Index(['b', 'c'], dtype='object')

In [75]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [76]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [77]:
obj2 = pd.Series([1.5,-2.5, 0], index = labels)

In [78]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is labels

True

In [80]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [81]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [82]:
'Ohio' in frame3.columns

True

In [83]:
2003 in frame3.index

False

In [84]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [85]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [86]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [87]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [88]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [89]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [90]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [91]:
obj3.reindex(range(6), method ='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [92]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [93]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [94]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [95]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [97]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [98]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [99]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [100]:
new_obj = obj.drop('c')

In [101]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [102]:
obj.drop(['b', 'c'])

a    0.0
d    3.0
e    4.0
dtype: float64

In [103]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [104]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [111]:
data.drop(['two', 'four'], axis = 1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [112]:
obj.drop('c', inplace=True)

In [113]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [115]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj['b']

1.0

In [117]:
obj[1]

1.0

In [118]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [119]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [120]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [121]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [123]:
obj['b' : 'c']

b    1.0
c    2.0
dtype: float64

In [124]:
obj['b':'c']=5

In [125]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [126]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [127]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [129]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [130]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [131]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [133]:
data[data<5] = 0

In [134]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [136]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [137]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [138]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [139]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [146]:
data.iloc[:, :3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [147]:
ser = pd.Series(np.arange(3.))

In [148]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [149]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [150]:
ser[:1]

0    0.0
dtype: float64

In [151]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [152]:
ser.iloc[:1]

0    0.0
dtype: float64

In [153]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index = ['a','c','e','f','g'])

In [154]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [155]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [156]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [157]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorada'])

In [158]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [159]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorada  6.0  7.0  8.0

In [160]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [161]:
df1 + df2

b   c     d   e
Colorada  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [162]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [163]:
df1

A
0  1
1  2

In [164]:
df2

B
0  3
1  4

In [165]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [167]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns = list('abcde'))

In [168]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [169]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [170]:
df2.loc[1, 'b'] = np.nan

In [171]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [172]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [173]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [174]:
df1.reindex(columns=df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [175]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [176]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [177]:
arr = np.arange(12.).reshape((3,4))

In [178]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [179]:
arr[0]

array([0., 1., 2., 3.])

In [182]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [186]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [184]:
series = frame.iloc[0]

In [185]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [187]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [188]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [192]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [193]:
series2

b    0
e    1
f    2
dtype: int64

In [194]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [196]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [197]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [198]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [199]:
np.abs(frame)

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [200]:
f = lambda x: x.max() -x.min()

In [201]:
frame.apply(f)

b    9.0
d    9.0
e    9.0
dtype: float64

In [206]:
frame.apply(f, axis = 'columns')

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

In [207]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [208]:
frame.apply(f)

b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

In [209]:
format = lambda x: '%.2f' % x

In [210]:
frame.applymap(format)

b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [211]:
frame['e'].map(format)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object

In [212]:
obj = pd.Series(range(4), index=['d', 'a','b','c'])

In [213]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [217]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index=['three', 'one'],
                     columns=['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [216]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [218]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [219]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [220]:
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [221]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [222]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [223]:
frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})

In [224]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [226]:
frame.sort_index(axis=1)

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [227]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [228]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [229]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [230]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [231]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [232]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                      'c':[-2,5,8,-2.5]})

In [233]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [234]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [235]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [236]:
obj.index.is_unique

False

In [237]:
obj['a']

a    0
a    1
dtype: int64

In [238]:
obj['c']

4

In [239]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [240]:
df

0         1         2
a -0.488139 -0.036472  0.418268
a  0.121980 -0.858219  0.784172
b  0.995445  2.142870 -1.167608
b  0.475178 -0.364187 -1.749984

In [241]:
df.loc['b']

0         1         2
b  0.995445  2.142870 -1.167608
b  0.475178 -0.364187 -1.749984

In [242]:
df = pd.DataFrame([[1.4, np.nan], [7.1,-4.5],
                   [np.nan, np.nan],[0.75,-1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [243]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [244]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [246]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [248]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [249]:
df.idxmax()

one    b
two    d
dtype: object

In [250]:
df.idxmax(axis=1)

a    one
b    one
c    NaN
d    one
dtype: object

In [252]:
df.cumsum(axis=1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [257]:
obj = pd.Series(['a','a','b','c']*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [256]:

obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [258]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [262]:
!pip install pandas-datareader

In [263]:
import pandas_datareader.data as web

In [266]:
all_data = {ticker:web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [267]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [268]:
volume = pd.DataFrame({ticker:data['Volume']
                      for ticker, data in all_data.items()})

In [269]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2016-11-18   27.635000   27.415001   27.430000   27.514999  113715600.0   
 2016-11-21   27.997499   27.502501   27.530001   27.932501  117058400.0   
 2016-11-22   28.105000   27.850000   27.987499   27.950001  103862000.0   
 2016-11-23   27.877501   27.582500   27.840000   27.807501  109705600.0   
 2016-11-25   27.967501   27.737499   27.782499   27.947500   45903600.0   
 ...                ...         ...         ...         ...          ...   
 2021-11-11  149.429993  147.679993  148.960007  147.869995   41000000.0   
 2021-11-12  150.399994  147.479996  148.429993  149.990005   63632600.0   
 2021-11-15  151.880005  149.429993  150.369995  150.000000   59222800.0   
 2021-11-16  151.490005  149.339996  149.940002  151.000000   59256200.0   
 2021-11-17  155.000000  150.990005  151.000000  153.490005   88446200.0   
 
  

In [270]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2016-11-18   25.899372  121.911011   56.112110   760.539978
2016-11-21   26.292355  123.720039   56.586304   769.200012
2016-11-22   26.308826  123.644005   56.828045   768.270020
2016-11-23   26.174694  123.119568   56.158596   760.989990
2016-11-25   26.306475  124.001251   56.279469   761.679993
...                ...         ...         ...          ...
2021-11-11  147.869995  120.269997  331.822906  2934.959961
2021-11-12  149.990005  118.959999  336.105103  2992.909912
2021-11-15  150.000000  118.870003  335.456299  2987.760010
2021-11-16  151.000000  118.459999  338.890015  2981.520020
2021-11-17  153.490005  118.059998  339.119995  2981.239990

[1258 rows x 4 columns]

In [271]:
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2016-11-18  113715600.0  3118754.0  27686300.0  1547100
2016-11-21  117058400.0  4850407.0  19652600.0  1330600
2016-11-22  103862000.0  2898257.0  23206700.0  1593100
2016-11-23  109705600.0  2356324.0  21848900.0  1478400
2016-11-25   45903600.0  1679144.0   8409600.0   587400
...                 ...        ...         ...      ...
2021-11-11   41000000.0  4643300.0  16849800.0   623200
2021-11-12   63632600.0  5414800.0  23822000.0   852000
2021-11-15   59222800.0  5046300.0  16723000.0   812400
2021-11-16   59256200.0  4750800.0  20886800.0   862700
2021-11-17   88446200.0  4041700.0  19016700.0   763400

[1258 rows x 4 columns]

In [272]:
returns = price.pct_change()

In [273]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-11-11 -0.000338  0.000416  0.004927  0.000832
2021-11-12  0.014337 -0.010892  0.012905  0.019745
2021-11-15  0.000067 -0.000757 -0.001930 -0.001721
2021-11-16  0.006667 -0.003449  0.010236 -0.002089
2021-11-17  0.016490 -0.003377  0.000679 -0.000094

In [274]:
returns['MSFT'].corr(returns['IBM'])

0.504581753214551

In [275]:
returns['MSFT'].cov(returns['IBM'])

0.00014397412988556205

In [276]:
returns.MSFT.corr(returns.IBM)

0.504581753214551

In [277]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.437524  0.736184  0.660502
IBM   0.437524  1.000000  0.504582  0.473856
MSFT  0.736184  0.504582  1.000000  0.777855
GOOG  0.660502  0.473856  0.777855  1.000000

In [278]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000138  0.000241  0.000212
IBM   0.000138  0.000275  0.000144  0.000133
MSFT  0.000241  0.000144  0.000296  0.000227
GOOG  0.000212  0.000133  0.000227  0.000287

In [279]:
returns.corrwith(returns.IBM)

AAPL    0.437524
IBM     1.000000
MSFT    0.504582
GOOG    0.473856
dtype: float64

In [280]:
returns.corrwith(volume)

AAPL   -0.073282
IBM    -0.137943
MSFT   -0.062679
GOOG   -0.113262
dtype: float64

In [281]:
obj = pd.Series(['b','a','d','a','a','b','b','c','c'])

In [282]:
uniques = obj.unique()

In [283]:
uniques

array(['b', 'a', 'd', 'c'], dtype=object)

In [284]:
obj.value_counts()

a    3
b    3
c    2
d    1
dtype: int64

In [285]:
pd.value_counts(obj.values, sort= False)

d    1
b    3
c    2
a    3
dtype: int64

In [286]:
obj

0    b
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [287]:
mask = obj.isin(['b','c'])

In [288]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [290]:
obj[mask]

0    b
5    b
6    b
7    c
8    c
dtype: object